id: I34B44D30
legacy_id: P010719
ocr_import_info:
  bdrc_scan_id: W24184
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T15:48:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:26:35.832337+00:00'
last_modified: 2022-09-02 13:26:46.217069
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24184
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW24184
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ས་སྐྱ་པའི་ཆོས་སྤྱོད།
statistics:
  ocr_word_mean_confidence_index: 0.600115508080979
  ocr_word_median_confidence_index: 0.6299999952316284
quality: null
bases:
  I1CZ956:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ956
      total_pages: 80
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ956.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.600115508080979
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
